name: GeyserSkinManager
version: ${project.version}
main: com.github.camotoy.geyserskinmanager.spigot.GeyserSkinManager
api-version: 1.16
softdepend: [ floodgate-bukkit, Geyser-Spigot ]
authors: [ Camotoy ]
